services:
  postgres:
    image: 'postgres:18.4'
    environment:
      - 'POSTGRES_DB=currencydb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
