spring.application.name=CurrencyExchanger
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.open-in-view=false
spring.flyway.validate-migration-naming=true
frankfurter.base-url=https://api.frankfurter.dev/v2
frankfurter.connect-timeout=2s
frankfurter.read-timeout=3s
